### PR TITLE
Update mws.yml

### PR DESCRIPTION
**Pull request by luca-a**

### CODE REVIEW

**Comment by mpontus** [comment]
Thank you for your contribution, @luca-a!

**Comment by ellemwano** [comment]
Thank you @luca-a. Apologies once again :)

**Comment by luca-a** [comment]
Don't worry @ellemwano it wasn't a problem at all 👍. Thanks @mpontus and @ellemwano for the great work, keep it up 😄

**Comment by ellemwano** [comment]
Thank you very much @luca-a. Really appreciated :)

**Pull request merged**
