### PR TITLE
Child Radio Tuner > ABND > Rares Serban

### PR DESCRIPTION
**Pull request by rareserban**
Hello, here comes my app :)

### CODE REVIEW

**Comment by ellemwano** [comment]
Hi Rares. Congratulations on you app! I remember you sharing it some time ago on Slack. Great work! However, I'm afraid it cannot be added to the website as only Udacity course projects are showcased here. So you're welcome to add one your ABND projects instead. I'm sorry and I hope you'll understand. Thank you :)

**Comment by rareserban** [comment]
Hello,

This project was started in Musical structure app. This is why was never public on github. I passed by sending as archive. Then private repo. 

Why is it not a "permited" one? Is done with mentor support. And collaboration with colleagues. Translating and alpha testing. 

It is a bad example as I took a project from course to the next level?

**Comment by OyaCanli** [comment]
Hi @rareserban! Congratulations again for your app, it looks great!
The thing is, we decided to show only the projects we have done for this nanodegree in this website. (For ABND it means one of the nine projects we submitted.) Because many of us keep doing extra projects after ND; some of us made group projects, some of us went on with advanced courses.. We had to decide what will be shown in this website and what won't be shown and this is the frame we defined for this website.
Is this the project you submitted for musical structure app? I mean, it's ok to polish your app later. But when it changes soo much and becomes completely different and doesn't conform to project specifications anymore, then it is like another project. 
Please don't misunderstand us. We are not a jury here and we are not evaluating the quality of projects. And your app is great, in fact it is far better than ABND standards. It is just that, we defined some ground rules for this website from the beginning and we're trying to stick to that.

**Comment by rareserban** [comment]
For musical structure I submitted a fully functional music streaming app. And I did submitted it as a archive not repo because it inspired me to do this app.

Strangely, when I told Joana and the others about the app they told me to post it here as welk. I did not do it back then as was in alpha. So here I am.

**Comment by ellemwano** [comment]
Hi again Rates. Please do not take this personally. There is nothing wrong with your project. We all acknowledge the great amount of work you've put into it and we've praised you for it.. Just understand that, as Oya explained, we had to set some rules regarding the projects to include here and it was decided from the start to only accept the course projects, so as to treat all students equally (as Udacity ND projects are the only things we all had in common, even if different for each track). Your submission is not a Udacity ND project so I'm afraid we cannot include it. We have to be fair here and I really hope you can understand that.
On a side note, this website was built by students and is run by students, not by Udacity. CMs are not involved in it.

**Comment by OyaCanli** [comment]
@rareserban Would you like to add your music streaming app to the website? (If you still have that version through version control) It doesn't matter if you don't want to share a public repository. You may prepare screenshots, may be a youtube video or a github page or similar, to present your project.

**Comment by rareserban** [comment]
Aaa.. so I should understand that here are the initial apps, as where approved when where submitted as students right? Next day where published in Play Store! No changes. 

I thought that here we where supposed to present what one can do if he/she works hard enough. As I did and still do, minimum 10 hours a day coding. Not where to stop to meet the specs. To motivate other students.

Anyway. If deep inside you feel that you guys are right and you are doing the right, fair thing, just reject and comment. Stand-up, reject and write it down.

Thank you again :)

**Comment by ellemwano** [comment]
@rareserban. I'm sorry you see if that way. As Oya explained before, updates/improvements are welcome, as long as your app stays close to the original project. Put it this way: if the Udacity ABND course lead was to browse this website, would they recognise which ABND project your app correspond to? 
If you do not wish to modify your entry to add one of your ABND projects, I will close this PR. Feel free to open a new one at any time. Thank you :)

**Comment by rareserban** [comment]
The app is exactly a musical structure app. But evolved as time passed by. As it is normal to happen. If Udacity course leads where to browse, or the mentors or the reviewer for that matter, they would know for sure. Maybe this is why they adviced back then to post it here.
Anyway, thank you and is good that the discussion will remain here as long as the repo.

**Pull request closed without merging**
