### PR TITLE
Update abnd.yml

### PR DESCRIPTION
**Pull request by Weyinmik**

### CODE REVIEW

**Comment by Weyinmik** [comment]
Thank you @mpontus , I just added my project and banner details, kindly check my last pull request.

**Comment by ellemwano** [comment]
Thank you for adding your project @Weyinmik! :)

**Comment by Weyinmik** [comment]
Thank you @ellemwano !

**Comment by ellemwano** [comment]
You're welcome :) You might want to change your banner later. Maybe put 3 screens next to each other as others did?

**Pull request merged**
